name: Lint Check

on:
  push:
    branches:
      - master # You can specify the branch you want to trigger the lint check on

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install # Or yarn install if you're using Yarn

      - name: Lint code
        run: npm run lint:test # Replace with your linting command
