version: "3.4"

services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres
    ports:
      - 23432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data-latest
  redis:  
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379

volumes:
  postgres-data: {}