export const BCH_MIN_TX_FEE = 8500
export const BTC_MIN_TX_FEE = 1000
export const DOGE_MIN_TX_FEE = 545000000
export const LTC_MIN_TX_FEE = 4500
export const DASH_MIN_TX_FEE = 1000

export const BTC_CASH_DEFAULT_SUGGESTED_TRANSACTION_FEE = 1
export const LTC_DEFAULT_SUGGESTED_TRANSACTION_FEE = 1
export const DASH_DEFAULT_SUGGESTED_TRANSACTION_FEE = 127
